### ISSUE TITLE
Adding encryption

### ISSUE THREAD

**Issue by sofiatti** [computablelabs/dapp-universities#6]
**As a** person going through the demo, **I want** to use encryption **so that** I can understand basic concepts of safely handling data. 

### Acceptance Criteria
- [x] Data is encrypted when at rest
- [x] Keys are stored in a separate place
Please also note:

1. The "key management" and user model is super trivial at first: it's a JSON with user tuples as `("email", "pwd-hash")` based on `bcrypt_sha256`
1. In the future, we should consider using metamask 
1. If a conversation about this issue is happening when it is being worked on (i.e., has an assignee),
the outcomes should be documented here (not in the comments).

### Resources:

Add image here.

**Comment by rbharath** [comment]
Copying over some notes from in-person discussion. The flip-side of encryption is user authentication. If we want our Dapps to be able to submit votes to Computable contracts, we probably will need users to authenticate with metamask and set up a flow so that the user's metamask plugin performs authorization for actions taken on their behalf. The reviewer flow (#10) will likely incorporate metamask as well

Here's a potentially useful links
https://hackernoon.com/never-use-passwords-again-with-ethereum-and-metamask-b61c7e409f0d
https://medium.com/coinmonks/expressjs-user-authentication-with-metamask-meta-auth-630b6da123ef

**Comment by SUICIDALcow** [comment]
@sofiatti, do you have a preferred encryption strategy for this?

**Comment by SUICIDALcow** [comment]
@sofiatti, do we have a preference on the encryption strategy used? You mention SHA256, but that is a 1-way hashing algorithm, which works fine for user authentication and passwords, but we’ll need something symmetric for encrypting our off-chain data. I’m guessing AES256 is fine for this?

**Comment by sofiatti** [comment]
@SUICIDALcow, closing this issue because it seems like you're done. Feel free to re-open.
